### ISSUE TITLE
Problem getting PDF

### ISSUE THREAD

**Issue by MichalSkoula** [webapix/mygls-sdk#1]
Hello,

I have added a parcel in test api environment via **PrintLabels** method. I get ParcelNumber, ParcelId,...

Then I want to get PDFs… but if I try **GetParcelStatuses** with parcelNumber, I get error 26 - Parcel not found with current settings
 

But when I try to get it via **GetPrintedLabels**, i get error 18 - Parcel label is already generated 

So my question is, how can I get PDF?

**Comment by MichalSkoula** [comment]
I want first add parcel to system, but generate PDF anytime after, with different offset etc. Because of that I cannot use PDFs directly from PrintLabels.

**Comment by zsocakave** [comment]
Hello,

I think you should use the PrepareLabels method instead of PrintLabels, then you can download it later with GetPrintedLabels request.

From the MyGLS docs: “PrintLabels Calls both PrepareLabels and GetPrintedLabels in one step.”

You can download the labels only once, unfortunatelly MyGLS doesn't support calling PrintLabels multiple times for the same parcel.

**Comment by MichalSkoula** [comment]
I think here is a wrong endpoint:

https://github.com/webapix/mygls-sdk/blob/b8bae0b62bee85e58eb66348e5b5563fc1597b85/src/Requests/PrepareLabels.php#L14

it should be PrepareLabels instead of PrintLabels

**Comment by MichalSkoula** [comment]
Then it works.

**Comment by zsocakave** [comment]
Thank you for your feedback, we fixed the wrong endpoint in 1.0.2.
